# Generated by Django 5.0.6 on 2024-12-23 19:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 1), help_text='Date is set to the first day of the month'),
        ),
        migrations.AddField(
            model_name='part',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='open_order',
            field=models.IntegerField(default=1, help_text='Open order quantity defined at the start of the month'),
            preserve_default=False,
        ),
    ]
