# Generated by Django 5.0.6 on 2024-12-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_part_date_part_date_added_part_open_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='additional_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
