# Generated by Django 5.0.6 on 2024-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_part_additional_order_part_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='part',
            name='previous_day_balance',
            field=models.IntegerField(default=0),
        ),
    ]
