# Generated by Django 5.0.6 on 2024-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_date_part_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
