# Generated by Django 5.0.6 on 2024-12-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_part_production_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='part',
            name='previous_day_balance',
        ),
        migrations.RemoveField(
            model_name='part',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='part',
            name='order_date',
            field=models.DateField(blank=True, help_text='User-defined order date', null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='production_date',
            field=models.DateField(blank=True, help_text='User-defined production date', null=True),
        ),
    ]
