# Generated by Django 5.0.6 on 2024-12-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_part_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('additional_order', models.IntegerField(default=0, help_text='Additional order for the day')),
                ('quantity_dispatched', models.IntegerField(default=0, help_text='Quantity dispatched for the day')),
                ('remaining_quantity', models.IntegerField(default=0, help_text='Remaining balance after production update')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_updates', to='dashboard.part')),
            ],
        ),
    ]
