# Generated by Django 5.0.6 on 2024-12-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_productionupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionupdate',
            name='additional_order',
            field=models.IntegerField(blank=True, default=0, help_text='Additional order for the day (optional)', null=True),
        ),
    ]
